# Package info
# <<< EDIT THESE! >>>
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "")
set(CPACK_PACKAGE_VENDOR "")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "0")

# <<< EDIT WHEN DIFFERENT >>>
set(AUTOCPACK_PROJECT_NAME ${PROJECT_NAME})

# <<< UNCOMMENT THESE WHEN USING ICONS >>>
# set(AUTOCPACK_W32_ICON "${CMAKE_SOURCE_DIR}/logo/winicon.rc")
# set(AUTOCPACK_OSX_IDENTIFIER "net.synthi.${AUTOCPACK_PROJECT_NAME}")
# set(AUTOCPACK_OSX_PLIST_PATH "${CMAKE_SOURCE_DIR}/Info.plist.in")
# set(AUTOCPACK_OSX_APP_ICON synthesis)
# set(AUTOCPACK_OSX_ICONS "${CMAKE_SOURCE_DIR}/logo/${AUTOCPACK_OSX_APP_ICON}.icns")
